name: irl-imitation
channels:
  - defaults
  - conda-forge
  - glemaitre
  - akode
dependencies:
  - cvxopt
  - ipykernel
  - jupyter
  - matplotlib
  - pandas
  - pip
  - python=2.7
  - seaborn
  - tabulate
  - tensorflow
  - pip:
    # - tensorflow==1.14.0
    # - setuptools==40.6.3
